### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xqozbd**
Fixed a typo

### CODE REVIEW

**Comment by xqozbd** [comment]
Just a few typo fixes, Nothing too big

**Comment by nocontent06** [comment]
Hey! Thanks for updating! 
It's actually just 1 Typo, because  "wen ETA" is a phrase said by jailbreakers speaking broken English when they ask for an ETA. Developers usually answer with "eta son" which means "ETA: soon"

**Comment by xqozbd** [comment]
Okay, I will undo that commit and I will let you review it again

**Comment by xqozbd** [comment]
Okay ready for review

**Comment by xqozbd** [comment]
Any update??

**Comment by nocontent06** [comment]
Thanks. I didn't see that "releases" :)

**Pull request merged**
